from time import sleep

def menu():
    print('='*50+' SISTEMA DE APOSTAS '+'='*50)
    print('A) => Calculo de Acertos Consecutivos                    | B) => Tabela de Probabilidades do Jogo Blackjack 21')
    print('C) => Relações de Probabilidades/ODDs dos Cassinos       | D) => Método Múltiplo 1:0,2:0,3:0') 
    print('E) => Estratégia: ZERO na Roleta Americana               | F) => Estratégia: Jogo do Avião (Crash)') 
    print('G) => Estratégia: Double (Blaze)                         | H) => Segredos do Lightning Dice (SportingBet)') 
    print('I) => Probabilidades a partir do Saldo de Gols (Futebol) | J) => Probabilidades: Rumo da Partida (Futebol)') 
    print('K) => Probabilidades do Bingo (Cartela cheia)            | L) => Sair')
    print('')

def menu_risco():
    print('='*50+' SELECIONE O RISCO '+'='*50)
    print('A) => Experiente e Veloz (Alto Risco)')
    print('B) => Conservador (Médio Risco)')
    print('C) => Pequenos ganhos pequenas perdas (Baixo Risco)')
    print('')

def menu_futebol():
    print('='*50+' SELECIONE O RESULTADO FINAL DO JOGO '+'='*50)
    print('A) => 0 GOLS (0-0)')
    print('B) => 1 GOL (1-0/0-1)')
    print('C) => 2 GOLS (2-0/0-2/1-1')
    print('D) => 3 GOLS (3-0/0-3/2-1/1-2')
    print('E) => 4 GOLS (4-0/0-4/3-1/1-3/2-2')
    print('F) => GOLEADA +5 GOLS')
    print('G) => EMPATES COM GOLS (1-1/2-2/3-3)')
    print('')

def menu_futebol_A():
    print('='*50)
    print('Com 0 GOLS o único placar disponivel é o 0-0')
    print('Raramente uma partida de Futebol ocorre eventos onde nenhum gol é realizado')
    print('Porém os ganhos nas casas de apostas multiplicam por x10 em média para esse resultado')
    print('JOGOS EM VANTAGEM: Ambas com Defesa Forte')
    print('')

def menu_futebol_B():
    print('='*50)
    print('Com 1 GOL temos dois placares possíveis 1-0 e 0-1')
    print('Para que esse evento ocorra um dos dois tempos do jogo nenhum gol deve ser realizado')
    print('1º TEMPO (0 gols): Se nenhum gol for realizado, sua chance de vitória aumenta para o segundo tempo')
    print('1º TEMPO (1 gol): Se um gol for realizado, então você está em desvantagem por conta do tempo')
    print('JOGOS EM VANTAGEM: Ambas com Defesa Forte')
    print('')

def menu_futebol_C():
    print('='*50)
    print('Com 2 GOLS temos três placares possíveis 2-0, 0-2 e 1-1')
    print('Para que esse evento ocorra deve haver um gol em cada tempo ou 2 gols em um dos dois tempos')
    print('1º TEMPO (0 gols): Se nenhum gol for realizado, sua chance de vitória aumenta para o segundo tempo')
    print('1º TEMPO (1 gol): Se um gol for realizado, sua chance de vitória aumenta para o segundo tempo visto que respeita-se o andamento do jogo')
    print('1º TEMPO (2 gols): Se dois gols forem realizados, para que você ganhe, o segundo tempo deverá haver mais defesa do que ataques')
    print('JOGOS EM VANTAGEM: Uma com Defesa forte e outra em contra-ataque')
    print('')

def menu_futebol_D():
    print('='*50)
    print('Com 3 GOLS temos quatro placares possíveis 3-0, 0-3, 2-1 e 1-2')
    print('Para que esse evento ocorra o jogo deve ocorrer em um formato mais agressivo')
    print('1º TEMPO (0 gols): Se nenhum gol for realizado, sua chance de vitória cai para o segundo tempo')
    print('1º TEMPO (1 gol): Se um gol for realizado, sua chance de vitória aumenta bastante para o segundo tempo')
    print('1º TEMPO (2 gols): Se dois gols forem realizados, dependendo do numero de tentativas ao gol de ambos os times isso contará para sua vitória')
    print('1º TEMPO (3 gols): Se dois gols forem realizados, você está totalmente em desvantagem por aqui, visto que o jogo não dá aberturas para que o segundo tempo seja sem gols')
    print('JOGOS EM VANTAGEM: Uma com Defesa forte e outra em contra-ataque / Dois times em contra-ataque')
    print('')

def menu_futebol_E():
    print('='*50)
    print('Com 4 GOLS temos cinco placares possíveis 4-0, 0-4, 3-1, 1-3 e 2-2')
    print('Para que esse evento ocorra o jogo deve ocorrer em um formato mais agressivo')
    print('1º TEMPO (0 gols): Se nenhum gol for realizado, você está em total desvantagem')
    print('1º TEMPO (1 gol): Se um gol for realizado, sua chance de vitória cai para o segundo tempo')
    print('1º TEMPO (2 gols): Se dois gols forem realizados, sua chance de vitória aumenta para o segundo tempo')
    print('1º TEMPO (3 gols): Se dois gols forem realizados, se Ambas marcaram você está com Vantagem, se Ambas não marcaram você está em Desvantagem')
    print('1º TEMPO (4 gols): É muito raro isso ocorrer, mas se ocorrer você está completamente em desvantagem')
    print('JOGOS EM VANTAGEM: Ambos os times com defesa fraca e sem poder de ataque/Dois times em contra-ataque')
    print('')

def menu_futebol_F():
    print('='*50)
    print('Com 5 GOLS ou mais, 95% das vezes um dos times é bastante agressivo e dominou a fraqueza do adversário')
    print('Para que esse evento ocorra o jogo deve ocorrer em um formato SUPER agressivo')
    print('1º TEMPO: Se houver 0 o 1 Gols no 1º Tempo você estará completamente em desvantagem')
    print('1º TEMPO: Caso ocorra de 2 a 4 Gols sua vantagem cresce cada vez mais com o numero de gols')
    print('JOGOS EM VANTAGEM: Jogo em formato Agressivo com Odds bem distantes uma das outras')
    print('')

def menu_futebol_G():
    print('='*50)
    print('Apostar no empate com gols abre janela para dois possíveis resultados que saem bastante 1-1 e 2-2')
    print('Claro que raramente ocorrem empates como 3-3 ou 4-4 e assim sucessivamente mas quase não se vê')
    print('Pelas estatísticas de 20 a 25% de todos os jogos acabam em Empates com Gols e apenas 7% em 0-0')
    print('É necessário que ambos os times possuam uma força de ataque para que esse evento ocorra')
    print('JOGOS EM VANTAGEM: Ambos os times saibam atacar independente de sua defesa')
    print('')

def blackjack():
    print('='*50+' BLACKJACK 21 '+'='*50)
    print('='*20+' PROBABILIDADE DE TER A SOMA ABAIXO DE 17 PONTOS (ZONA SEGURA)'+'='*20)
    sleep(0.5)
    print('2 cartas = 74,81 %')
    print('3 cartas = 28,54 %')
    print('4 cartas = 6,35 %')
    print('5 cartas = 0,91 %')
    sleep(1)
    print('='*20+' PROBABILIDADE DE TER A SOMA ENTRE 17 E 20 PONTOS (ZONA STOP)'+'='*20)
    sleep(0.5)
    print('2 cartas = 25,18 %')
    print('3 cartas = 25,61 %')
    print('4 cartas = 12 %')
    print('5 cartas = 3,06 %')
    sleep(1)
    print('='*20+' PROBABILIDADE DE BATER 21 PONTOS (VITÓRIA TOTAL)'+'='*20)
    sleep(0.5)
    print('2 cartas = 4,82 %')
    print('3 cartas = 8 %')
    print('4 cartas = 4,26 %')
    print('5 cartas = 1,41 %')
    print('6 cartas = apenas a sequencia A/2/3/4/5/6 seria vitoriosa')
    sleep(1)
    print('='*20+' PROBABILIDADE DE EXTRAPOLAR 21 PONTOS (ZONA VERMELHA)'+'='*20)
    sleep(0.5)
    print('2 cartas = X')
    print('3 cartas = 37,82 %')
    print('4 cartas = 77,36 %')
    print('5 cartas = 94,61 %')
    print('6 cartas = 99,97 %')
    print('='*50)
    sleep(1)

def odd_prob():
    print('='*20+' PROBABILIDADES RELACIONADAS A SUAS ODDS '+'='*20)
    sleep(1)
    print('|   ODD  | CHANCES |')
    sleep(0.3)
    print('|   1.11 |   90 %  |')
    sleep(0.3)
    print('|   1.25 |   80 %  |')
    sleep(0.3)
    print('|   1.33 |   75 %  |')
    sleep(0.3)
    print('|   2.00 |   50 %  |')
    sleep(0.3)
    print('|   2.50 |   40 %  |')
    sleep(0.3)
    print('|   3.30 |   30 %  |')
    sleep(0.3)
    print('|   4.00 |   25 %  |')
    sleep(0.3)
    print('|   5.00 |   20 %  |')
    sleep(0.3)
    print('|   7.00 |   15 %  |')
    sleep(0.3)
    print('|   9.00 |   11 %  |')
    sleep(0.3)
    print('|  11.00 |   10 %  |')
    sleep(0.3)
    print('|  15.00 |    7 %  |')
    sleep(0.3)
    print('|  21.00 |    5 %  |')
    sleep(0.3)
    print('|  26.00 |    4 %  |')
    sleep(0.3)
    print('|  34.00 |    3 %  |')
    sleep(0.3)
    print('|  51.00 |    2 %  |')
    sleep(0.3)
    print('| 101.00 |    1 %  |')
    sleep(0.3)
    print('='*50)
    sleep(1)

def placar_multiplo_A():
    print('='*20+' MÉTODO PLACAR MULTIPLO (ALTO RISCO) '+'='*20)
    sleep(1)
    print('Esse método consiste em alavancar uma aposta a cada jogo de Futebol:')
    print('1- Abra o site de apostas e para cada jogo há um time com odds menores para ganhar')
    print('2- O time que tem odds menores são os favoritos ou que tem maior chance de vencer a partida')
    print('3- Em relação as estatísticas a maioria desses jogos sempre termina com apenas um time marcando gols')
    print('4- A ideia é que você aposte sempre no placar multiplo (1:0/2:0/3:0)')
    print('5- Vamos apostar utilizando o Martingale começando por 1$: Quando você sair no Lucro você volta a apostar 1$ no próximo jogo')
    print('6- A cada perda acumulada em cada jogo você soma com o resultado anterior:')
    print('-'*30)
    print('(2º jogo = aposta 2$)')
    print('(3º jogo = aposta 3$ (2+1))')
    print('(4º jogo = aposta 5$ (3+2))')
    print('(5º jogo = aposta 8$ (5+3))')
    print('-'*30)
    print('7- Você perceberá que seu Lucro aumentará a medida que for usando o Martingale')
    print('8- Se dois times tem Odds quase iguais uma das outras, é recomendado não entrar nesse caso')
    print('='*50)
    sleep(1)

def placar_multiplo_B():
    print('='*20+' MÉTODO PLACAR MULTIPLO (MÉDIO RISCO) '+'='*20)
    sleep(1)
    print('Esse método consiste em apostar uma quantia somatória em todos os jogos de Futebol:')
    print('1- Abra o site de apostas e para cada jogo há um time com odds menores para ganhar')
    print('2- O time que tem odds menores são os favoritos ou que tem maior chance de vencer a partida')
    print('3- Em relação as estatísticas a maioria desses jogos sempre termina com apenas um time marcando gols')
    print('4- A ideia é que você aposte sempre no placar multiplo (1:0/2:0/3:0)')
    print('5- Comece apostando a mesma quantia (5$ por exemplo) em um determinado grupo de jogos')
    print('6- Determine a quantidade de jogos e a quantia e após o grupo de jogos acabar analise seus resultados')
    print('7- Se você terminar com um prejuizo 2x que seu valor apostado (-10 nesse caso) então no próximo grupo de jogos aposte com 10$')
    print('8- Na segunda vez que você apostar você vai ter uma visão clara dos resultados anteriores, isso te deixa uma vantagem')
    print('9- Ao fim do segundo grupo de jogos analise os resultados, se sair no Lucro a estratégia funcionou, retorne novamente apostando 5$')
    print('10- Porém se saiu no prejuizo aposte 15$ dessa vez sempre somando a aposta anterior (10+5)')
    print('11- Se dois times tem Odds quase iguais uma das outras, é necessário que você revise os ultimos 3 jogos desses dois times para ver se vale a pena apostar já que a Odd do Placar Multiplo estará maior')
    print('='*50)
    sleep(1)

def placar_multiplo_C():
    print('='*20+' MÉTODO PLACAR MULTIPLO (BAIXO RISCO) '+'='*20)
    sleep(1)
    print('Esse método consiste em apostar a mesma quantia em todos os jogos de Futebol:')
    print('1- Abra o site de apostas e para cada jogo há um time com odds menores para ganhar')
    print('2- O time que tem odds menores são os favoritos ou que tem maior chance de vencer a partida')
    print('3- Em relação as estatísticas a maioria desses jogos sempre termina com apenas um time marcando gols')
    print('4- A ideia é que você aposte sempre no placar multiplo (1:0/2:0/3:0) com a mesma quantia')
    print('5- As chances de ganhar com placar multiplo aumentam bastante com favoritismo da casa')
    print('6- Há casos bem raros onde se a casa pode ultrapassar os 3:0 e marcar mais gols')
    print('7- Se dois times tem Odds quase iguais uma das outras não é recomendado apostar')
    print('8- Comece apostando quantias baixas como 5$ em cada jogo')
    print('='*50)
    sleep(1)

def lightdice():
    print('='*20+' LIGHTNING DICE '+'='*20)
    sleep(1)
    print('O Jogo Lightning Dice consiste em jogar 3 dados aleatoriamente e somar seus valores:')
    print('Fazendo o calculo de arranjamento e combinação temos 56 possíveis resultados')
    print('A Soma entre os dados contem valores entre 3 (1:1:1) e 18 (6:6:6)')
    print('Podemos perceber que para dar 3 ou 18 os três dados precisam cair em 1:1:1 ou 6:6:6')
    print('Se apostarmos em um dos dois vamos ganhar x150 o valor apostado, a chance é de 1/56 nos dois casos')
    print('Essa chance equivale a 1,7 %')
    print('Apostando no 3 e no 18 temos 3,4 % para ganhar ou 2/56 e lucramos x75 do valor total apostado')
    print('-'*30)
    print('DUPLO: Há 36/56 combinações ou 64,2 % para que dois dados resultem em valores IGUAIS')
    print('TRIPLO: Há 6/56 combinações 10,7 % para que os três dados resultem em valores IGUAIS')
    print('-'*30)
    print('RAIO: O Raio incrementa em 5X o valor da ODD e eleva seu lucro se sua aposta sair vencedora')
    print('-'*30)
    print('1 Aposta: A chance do RAIO cair no numero escolhido é de 6,25 %')
    print('2 Apostas: A chance do RAIO cair no numero escolhido é de 12,5 %')
    print('3 Apostas: A chance do RAIO cair no numero escolhido é de 18,75 %')
    print('4 Apostas: A chance do RAIO cair no numero escolhido é de 25 %')
    print('5 Apostas: A chance do RAIO cair no numero escolhido é de 31,25 %')
    print('6 Apostas: A chance do RAIO cair no numero escolhido é de 37,5 %')
    print('='*50)
    sleep(1)

def rumo_partida():
    print('='*20+' RUMO DA PARTIDA '+'='*20)
    sleep(1)
    print('|  RUMO         | 1º TEMPO    | 2º TEMPO                |')
    sleep(0.3)
    print('| Casa/Casa     | 1:0/2:0/2:1 | Manter                  |')
    sleep(0.3)
    print('| Empate/Casa   | 0:0/1:1     | 1:0/2:0/2:1/3:1/3:2/4:2 |')
    sleep(0.3)
    print('| Zebra/Casa    | 0:1/0:2/1:2 | 2:1/3:2                 |')
    sleep(0.3)
    print('| Zebra/Zebra   | 0:1/0:2/1:2 | Manter                  |')
    sleep(0.3)
    print('| Empate/Zebra  | 0:0/1:1     | 0:1/0:2/1:2/1:3/2:3/2:4 |')
    sleep(0.3)
    print('| Casa/Zebra    | 1:0/2:0/2:1 | 1:2/2:3                 |')
    sleep(0.3)
    print('| Casa/Empate   | 1:0/2:0/2:1 | 1:1/2:2/3:3             |')
    sleep(0.3)
    print('| Zebra/Empate  | 0:1/0:2/1:2 | 1:1/2:2/3:3             |')
    sleep(0.3)
    print('| Empate/Empate | 0:0/1:1     | 0:0/1:1/2:2/3:3         |')
    sleep(0.3)
    print('='*50)
    sleep(1)

def bingo():
    print('='*20+' PROBABILIDADES DO BINGO '+'='*20)
    print('')
    sleep(1)
    print('Quantidade Total de Numeros do Bingo: 75')
    print('Quantidade Total de Numeros da Cartela: 25')
    print('Probabilidade de ter o 1º Numero sorteado: 33,33%')
    print('-'*50)
    print('Para que ocorra o primeiro ganhador pelo menos no minimo 25 numeros precisam ser sorteados')
    print('Porém a chance de que o jogador marque 25 numeros consecutivos é extremamente menor que 0,01%')
    print('Porém, a cada numero sorteado que você não marca sua chance de marcar o próximo aumenta')
    print('Importante: A Cartela cheia também depende do numeros de jogadores que estão jogando')
    print('-'*50)
    print('Utilize o Simulador abaixo para simular uma Probabilidade no Andamento do Jogo:')
    print('')
    
def descrevealto_E():
    print('-'*50)
    print('Essa estratégia serve justamente para gerenciar perdas e ganhos!')
    print('Essa estratégia tem limite de perda minima de -20,00!')
    print('-'*50)

def descrevemedio_E():
    print('-'*50)
    print('Essa estratégia serve justamente para gerenciar perdas e ganhos!')
    print('Essa estratégia tem limite de perda minima de -20,00!')
    print('-'*50)

def descrevebaixo_E():
    print('-'*50)
    print('Nessa estratégia você apostará a mesma quantia porém decidirá aonde entrar!')
    print('Essa estratégia apenas ajuda a dividir os valores igualmente entre as apostas através do seu capital total de giro!')
    print('-'*50)

def descrevealto_F():
    print('-'*50)
    print('Nessa estratégia você apostará usando a soma Martingale e sairá em uma ODD Determinada!')
    print('A Quantidade de apostas dependerá do tamanho do seu capital em jogo!')
    print('-'*50)

def descrevemedio_F():
    print('-'*50)
    print('Nessa estratégia você apostará usando a soma Martingale e sairá em uma ODD Fixa!')
    print('A Quantidade de apostas dependerá do tamanho do seu capital em jogo!')
    print('-'*50)

def descrevebaixo_F():
    print('-'*50)
    print('Nessa estratégia você apostará a mesma quantia e receberá a mesma quantia que apostou como Lucro!')
    print('-'*50)

def descrevealto_G():
    print('-'*50)
    print('Nessa estratégia você apostará no BRANCO usando a soma Martingale!')
    print('Você vai parar de apostar apenas quando atingir o BRANCO!')
    print('Essa estratégia confia que o BRANCO não demore bastante para sair e os GANHOS são absurdos!')
    print('Quanto mais tempo demorar, maior serão os GANHOS!')
    print('Recomenda-se ter uma quantia acima de R$ 1.000,00 para realizar essa estratégia!')
    print('-'*50)

def descrevemedio_G():
    print('-'*50)
    print('Nessa estratégia você apostará no BRANCO usando a soma específica da TABELA!')
    print('Você vai parar de apostar apenas quando atingir o BRANCO!')
    print('Essa estratégia equilibra para que você não tenha grandes prejuizos nem grandes ganhos!')
    print('Porém com o tempo a força do prejuizo pode criar um certo peso nessa estratégia!')
    print('-'*50)

def descrevebaixo_G():
    print('-'*50)
    print('Nessa estratégia você apostará no BRANCO repetindo o mesmo valor apostado!')
    print('O valor apostado será DOBRADO após não haver LUCRO MINIMO!')
    print('Essa estratégia equilibra para que você comece devagar e ganhando centavos muito pouco!')
    print('Com o tempo você cresce no valor das apostas e no Lucro porém leva mais tempo, é importante seguir a TABELA!')
    print('-'*50)